// src/config/audio.js

export const AUDIO_CONFIG = Object.freeze({
  MASTER_GAIN: 0.58,
  SFX_GAIN: 1.15,
  AMBIENCE_GAIN: 0.16,
  MUSIC: Object.freeze({
    ENABLED: true,
    STEP_MS: 180,
    GAIN: 0.075,
    BASS_GAIN: 0.11,
    LEAD_GAIN: 0.055,
    DRUM_GAIN: 0.045,
  }),
  COMBAT_BED: Object.freeze({
    ENABLED: true,
    WIND_GAIN: 0.05,
    THUNDER_GAIN: 0.07,
    THUNDER_MIN_DELAY_MS: 9000,
    THUNDER_MAX_DELAY_MS: 18000,
    PLAYBACK_RATE_MIN: 0.88,
    PLAYBACK_RATE_MAX: 1.04,
    DISTANT_FIRE_MIN_DELAY_MS: 3500,
    DISTANT_FIRE_MAX_DELAY_MS: 8500,
    DISTANT_FIRE_GAIN: 0.05,
  }),
  SFX: Object.freeze({
    SHOOT_MULTIPLIER: 1.45,
    IMPACT_MULTIPLIER: 1.25,
    HIT_MULTIPLIER: 1.2,
    FOOTSTEP_MULTIPLIER: 1.1,
    MOVEMENT_MULTIPLIER: 1.05,
  }),
});
