// src/config/constants.js

export const NETWORK_CONFIG = {
  SERVER_TICK_RATE: 60,
  SNAPSHOT_BROADCAST_RATE: 30,
  INPUT_SEND_RATE: 60,
  INTERPOLATION_BUFFER_MS: 100,
  INPUT_HISTORY_SIZE: 128,
  RECONCILIATION_THRESHOLD: 0.15,
};

export const GAME_CONFIG = {
  TICK_RATE: 60,
  MAX_PLAYERS: 4,
  PLAYER_SPEED: 8.0,
  PLAYER_JUMP_FORCE: 6.5,
  GRAVITY: -19.62,
  PLAYER_HEIGHT: 1.8,
  PLAYER_RADIUS: 0.4,
  CAMERA_HEIGHT_OFFSET: 1.6,
  CAMERA_HEIGHT_CROUCH: 1.0,
  CAMERA_HEIGHT_PRONE: 0.35,
  SPEED_MULT_CROUCH: 0.45,
  SPEED_MULT_PRONE: 0.2,
  MAX_HEALTH: 100,
  RESPAWN_TIME_MS: 3000,
  FOV: 75,
  NEAR_PLANE: 0.05,
  FAR_PLANE: 500,
  BOUNDARY_PADDING: 1.5,
  INTERPOLATION_DELAY_MS: 100,
  RECONCILIATION_THRESHOLD: 0.15,
  RECOIL_RECOVERY: 10.0,
  MAX_DECALS: 100,
  // Movement sway → accuracy (radians at full run)
  MOVE_SPREAD_MAX: 0.035,
  BOB_INTENSITY: 1.0,
};

export const INPUT_FLAGS = {
  FORWARD: 1 << 0,
  BACKWARD: 1 << 1,
  LEFT: 1 << 2,
  RIGHT: 1 << 3,
  JUMP: 1 << 4,
  SHOOT: 1 << 5,
  RELOAD: 1 << 6,
  CROUCH: 1 << 7,
  PRONE: 1 << 8,
};

export const FIRE_MODE = { SEMI: 'semi', AUTO: 'auto' };

export const STANCE = { STAND: 0, CROUCH: 1, PRONE: 2 };

/** Real-world-ish rates (ms between shots) */
export const WEAPON_CONFIG = {
  PISTOL: {
    ID: 1, SLOT: 0, NAME: 'Pistol',
    FIRE_RATE_MS: 280, DAMAGE: 30,
    MAGAZINE_SIZE: 12, RESERVE_AMMO: 36, RELOAD_TIME_MS: 1600, RANGE: 100,
    RECOIL_PITCH: 0.042, RECOIL_YAW_SPREAD: 0.012,
    SPREAD_BASE: 0, SPREAD_GROW: 0.01, SPREAD_MAX: 0.045, SPREAD_DECAY: 0.14,
    PELLETS: 1, FIRE_MODE: FIRE_MODE.SEMI, SFX: 'pistol',
  },
  SMG: {
    ID: 2, SLOT: 1, NAME: 'SMG',
    FIRE_RATE_MS: 75, DAMAGE: 13,
    MAGAZINE_SIZE: 30, RESERVE_AMMO: 90, RELOAD_TIME_MS: 2000, RANGE: 75,
    RECOIL_PITCH: 0.02, RECOIL_YAW_SPREAD: 0.022,
    SPREAD_BASE: 0, SPREAD_GROW: 0.014, SPREAD_MAX: 0.08, SPREAD_DECAY: 0.16,
    PELLETS: 1, FIRE_MODE: FIRE_MODE.AUTO, SFX: 'smg',
  },
  SHOTGUN: {
    ID: 3, SLOT: 2, NAME: 'Shotgun',
    FIRE_RATE_MS: 850, DAMAGE: 11,
    MAGAZINE_SIZE: 6, RESERVE_AMMO: 24, RELOAD_TIME_MS: 2600, RANGE: 30,
    RECOIL_PITCH: 0.1, RECOIL_YAW_SPREAD: 0.035,
    SPREAD_BASE: 0.045, SPREAD_GROW: 0.012, SPREAD_MAX: 0.11, SPREAD_DECAY: 0.22,
    PELLETS: 8, FIRE_MODE: FIRE_MODE.SEMI, SFX: 'shotgun',
  },
  RIFLE: {
    ID: 4, SLOT: 3, NAME: 'Rifle',
    FIRE_RATE_MS: 95, DAMAGE: 24,
    MAGAZINE_SIZE: 25, RESERVE_AMMO: 75, RELOAD_TIME_MS: 2200, RANGE: 160,
    RECOIL_PITCH: 0.03, RECOIL_YAW_SPREAD: 0.011,
    SPREAD_BASE: 0, SPREAD_GROW: 0.007, SPREAD_MAX: 0.05, SPREAD_DECAY: 0.11,
    PELLETS: 1, FIRE_MODE: FIRE_MODE.AUTO, SFX: 'rifle',
  },
};

export const WEAPON_LOADOUT = [
  WEAPON_CONFIG.PISTOL,
  WEAPON_CONFIG.SMG,
  WEAPON_CONFIG.SHOTGUN,
  WEAPON_CONFIG.RIFLE,
];

export const DEFAULT_WEAPON = WEAPON_CONFIG.PISTOL;

export function peerIdToNumeric(peerId) {
  if (typeof peerId === 'number' && Number.isFinite(peerId)) return peerId >>> 0;
  if (!peerId || typeof peerId !== 'string') return 1;
  let hash = 2166136261;
  for (let i = 0; i < peerId.length; i++) {
    hash ^= peerId.charCodeAt(i);
    hash = Math.imul(hash, 16777619);
  }
  return (hash >>> 0) || 1;
}
