// src/config/network.js

export const NETWORK_CONFIG = Object.freeze({
  SERVER_TICK_RATE: 60,
  CLIENT_TICK_RATE: 60,
  SNAPSHOT_BROADCAST_RATE: 20,
  INPUT_SEND_RATE: 60,
  INTERPOLATION_BUFFER_MS: 100,
  INTERPOLATION_MIN_MS: 50,
  INTERPOLATION_MAX_MS: 200,
  INPUT_HISTORY_SIZE: 128,
  MAX_INPUT_QUEUE: 16,
  MAX_GAME_EVENT_QUEUE: 32,
  MAX_SNAPSHOT_HISTORY: 16,
  LAG_COMPENSATION_MAX_MS: 200,
  HITBOX_HISTORY_TICKS: 180,
  NETWORK_CLOCK_SMOOTHING: 0.08,
  RECONCILIATION_ERROR_THRESHOLD: 0.08,
  RECONCILIATION_MAX_VISUAL_CORRECTION: 1.5,
  PEER_ID_HASH: Object.freeze({ OFFSET_BASIS: 2166136261, PRIME: 16777619 }),
  SIGNALING: Object.freeze({
    HOST: '', PORT: 443, PATH: '/', SECURE: true, DEBUG: 1,
    PING_INTERVAL_MS: 5000, RECONNECT_DELAY_MS: 1500,
  }),
  WEBRTC: Object.freeze({
    STUN_SERVERS: Object.freeze([
      Object.freeze({ urls: 'stun:stun.l.google.com:19302' }),
      Object.freeze({ urls: 'stun:stun1.l.google.com:19302' }),
      Object.freeze({ urls: 'stun:stun2.l.google.com:19302' }),
    ]),
    ICE_TRANSPORT_POLICY: 'all', SDP_SEMANTICS: 'unified-plan',
    SIGNALING_TIMEOUT_MS: 10000, DATA_CONNECTION_TIMEOUT_MS: 30000,
    TURN_CONFIG_TIMEOUT_MS: 5000, ICE_GATHERING_GRACE_MS: 1000,
    STATS_SAMPLE_DELAY_MS: 1500, REQUIRE_TURN_IN_PRODUCTION: false,
  }),
  TRANSPORT: Object.freeze({
    LABEL: 'p2p-fps-game', SERIALIZATION: 'binary',
    RELIABLE: true, MAX_BUFFERED_BYTES: 512 * 1024,
    MAX_PACKET_BYTES: 64 * 1024,
    BUFFER_HIGH_WATERMARK_BYTES: 256 * 1024,
    BUFFER_LOW_WATERMARK_BYTES: 64 * 1024,
  }),
  CHANNELS: Object.freeze({
    INPUT: Object.freeze({ reliable: false, ordered: true }),
    SNAPSHOT: Object.freeze({ reliable: false, ordered: false }),
    CONTROL: Object.freeze({ reliable: true, ordered: true }),
  }),
  HANDSHAKE: Object.freeze({ JOIN_TIMEOUT_MS: 10000 }),
  INVITATION_CODE: Object.freeze({
    LENGTH: 5, ALPHABET: 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789', MAX_RETRIES: 8,
  }),
});

export const PROTOCOL_CONFIG = Object.freeze({
  JOIN_REQUEST_SIZE: 3, CLIENT_INPUT_SIZE: 17,
  SNAPSHOT_HEADER_SIZE: 10, SNAPSHOT_ENTITY_SIZE: 45,
  JOIN_ACCEPT_SIZE: 18, WORLD_INIT_HEADER_SIZE: 5, GAME_EVENT_HEADER_SIZE: 5,
  PROTOCOL_VERSION: 1, MAX_SNAPSHOT_ENTITIES: 255,
  MAX_UINT8: 255, MAX_UINT16: 65535,
});
