// src/config/network.js

export const NETWORK_CONFIG = Object.freeze({
  SERVER_TICK_RATE: 60,
  CLIENT_TICK_RATE: 60,
  SNAPSHOT_BROADCAST_RATE: 20,
  INPUT_SEND_RATE: 60,
  INTERPOLATION_BUFFER_MS: 100,
  INPUT_HISTORY_SIZE: 128,
  MAX_SNAPSHOT_HISTORY: 16,
  INVITATION_CODE: Object.freeze({
    LENGTH: 5,
    ALPHABET: 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789',
  }),
});

export const PROTOCOL_CONFIG = Object.freeze({
  CLIENT_INPUT_SIZE: 16,
  SNAPSHOT_HEADER_SIZE: 10,
  SNAPSHOT_ENTITY_SIZE: 45,
  JOIN_ACCEPT_SIZE: 18,
  WORLD_INIT_HEADER_SIZE: 5,
  GAME_EVENT_HEADER_SIZE: 5,
  MAX_SNAPSHOT_ENTITIES: 255,
  MAX_UINT8: 255,
  MAX_UINT16: 65535,
});
