// src/config/render.js

export const RENDER_CONFIG = Object.freeze({
  MAX_PIXEL_RATIO: 2,
  MAX_RENDER_DELTA_SECONDS: 0.05,
  // Global guardrails for high-rate automatic weapons and multiplayer bursts.
  MAX_IMPACT_REACTIONS: 96,
  MAX_IMPACT_PARTICLES_PER_REACTION: 28,
  NETWORK_VISUAL_CORRECTION_SMOOTHING: 10,
  IMPACT_FLASH: Object.freeze({
    BULLET_MS: 90,
    BLOOD_MS: 70,
    SPARK_MS: 360,
    SPARK_COUNT: 11,
    BLOCK_COUNT: 5,
    SPARK_SPEED: 1.0,
    SPAWN_DELAY_MS: 105,
    SPAWN_OFFSET: 0.018,
    PATTERN_RADIUS: 0.075,
    TANGENT_DIRECTION: 0.9,
    TANGENTIAL_SPEED_MIN: 0.9,
    TANGENTIAL_SPEED_MAX: 2.4,
    NORMAL_SPEED_MIN: 0.8,
    NORMAL_SPEED_MAX: 2.2,
    DRAG_MIN: 1.2,
    DRAG_MAX: 2.8,
    GRAVITY: 5.5,
    SPARK_SIZE_MIN: 0.028,
    SPARK_SIZE_MAX: 0.065,
    SPARK_LENGTH_MIN: 0.14,
    SPARK_LENGTH_MAX: 0.34,
    BLOCK_SIZE_MIN: 0.045,
    BLOCK_SIZE_MAX: 0.085,
    FADE_DELAY_MS: 55,
    FADE_POWER: 2.2,
  }),
  MUZZLE_FLASH: Object.freeze({
    DURATION_SECONDS: 0.075,
    LIGHT_DISTANCE: 1.8,
    LIGHT_INTENSITY: 7.5,
  }),
  AIM: Object.freeze({
    FOV: 58,
    TRANSITION_SECONDS: 0.12,
    WEAPON_POSITION_X: 0.03,
    WEAPON_POSITION_Y: -0.18,
    WEAPON_POSITION_Z: -0.58,
    WEAPON_SCALE: 0.92,
    SENSITIVITY_MULTIPLIER: 0.65,
    WEAPON_POSES: Object.freeze({
      1: Object.freeze({ x: 0.03, y: -0.18, z: -0.58, pitch: 0.02, yaw: 0.02, roll: 0 }),
      2: Object.freeze({ x: 0.025, y: -0.17, z: -0.60, pitch: 0.015, yaw: 0.018, roll: 0 }),
      3: Object.freeze({ x: 0.02, y: -0.16, z: -0.62, pitch: 0.01, yaw: 0.015, roll: 0 }),
      4: Object.freeze({ x: 0.018, y: -0.17, z: -0.61, pitch: 0.012, yaw: 0.012, roll: 0 }),
    }),
  }),
  CROSSHAIR: Object.freeze({
    // Crosshair appearance is intentionally config-driven.
    COLOR: '#ffffff',
    OUTLINE_COLOR: '#000000',
    COLOR_MODE: 'accuracy',
    ACCURACY_COLOR_GOOD: '#72ff72',
    ACCURACY_COLOR_MID: '#ffd166',
    ACCURACY_COLOR_BAD: '#ff5c5c',
    OUTLINE_WIDTH: 0.8,
    ARMS_ENABLED: true,
    DOT_ENABLED: true,
    DOT_RADIUS_PX: 1.35,
    DOT_RADIUS_ADS_PX: 1.0,
    ARMS_OPACITY: 0.96,
    DOT_OPACITY: 0.98,
    RESTING_GAP_PX: 4,
    RESTING_LENGTH_PX: 6,
    RESTING_THICKNESS_PX: 2,
    MAX_MOVEMENT_GAP_PX: 18,
    MAX_SPRINT_GAP_PX: 30,
    MAX_BLOOM_GAP_PX: 10,
    AIM_GAP_PX: 1,
    AIM_LENGTH_PX: 4,
    MAX_LENGTH_PX: 9,
    RESPONSE: 24,
    MIN_SPEED: 0.02,
    MAX_SPEED: 10.8,
    BLOOM_SCALE: 105,
    FIRE_BLOOM_PX: 4,
    RECOIL_BLOOM_PX: 7,
  }),
  HEALTH_BAR: Object.freeze({ MAX_HEALTH_FALLBACK: 100 }),
  DEFAULT_REMOTE_WEAPON_ID: 1,
});
