// src/config/render.js

export const RENDER_CONFIG = Object.freeze({
  MAX_PIXEL_RATIO: 2,
  MAX_RENDER_DELTA_SECONDS: 0.05,
  NETWORK_VISUAL_CORRECTION_SMOOTHING: 10,
  IMPACT_FLASH: Object.freeze({
    BULLET_MS: 90,
    BLOOD_MS: 70,
    SPARK_MS: 180,
    SPARK_SPEED: 1.15,
    SPARK_SIZE_MIN: 0.04,
    SPARK_SIZE_MAX: 0.09,
    SPARK_LENGTH_MIN: 0.20,
    SPARK_LENGTH_MAX: 0.45,
  }),
  MUZZLE_FLASH: Object.freeze({
    DURATION_SECONDS: 0.075,
    LIGHT_DISTANCE: 1.8,
    LIGHT_INTENSITY: 7.5,
  }),
  AIM: Object.freeze({
    FOV: 58,
    TRANSITION_SECONDS: 0.12,
    WEAPON_POSITION_X: 0.03,
    WEAPON_POSITION_Y: -0.18,
    WEAPON_POSITION_Z: -0.58,
    WEAPON_SCALE: 0.92,
    SENSITIVITY_MULTIPLIER: 0.65,
    WEAPON_POSES: Object.freeze({
      1: Object.freeze({ x: 0.03, y: -0.18, z: -0.58, pitch: 0.02, yaw: 0.02, roll: 0 }),
      2: Object.freeze({ x: 0.025, y: -0.17, z: -0.60, pitch: 0.015, yaw: 0.018, roll: 0 }),
      3: Object.freeze({ x: 0.02, y: -0.16, z: -0.62, pitch: 0.01, yaw: 0.015, roll: 0 }),
      4: Object.freeze({ x: 0.018, y: -0.17, z: -0.61, pitch: 0.012, yaw: 0.012, roll: 0 }),
    }),
  }),
  CROSSHAIR: Object.freeze({
    RESTING_GAP_PX: 4,
    RESTING_LENGTH_PX: 6,
    RESTING_THICKNESS_PX: 2,
    MAX_MOVEMENT_GAP_PX: 18,
    MAX_SPRINT_GAP_PX: 30,
    MAX_BLOOM_GAP_PX: 10,
    AIM_GAP_PX: 1,
    AIM_LENGTH_PX: 4,
    MAX_LENGTH_PX: 9,
    RESPONSE: 24,
    MIN_SPEED: 0.02,
    MAX_SPEED: 10.8,
    BLOOM_SCALE: 105,
    FIRE_BLOOM_PX: 4,
    RECOIL_BLOOM_PX: 7,
  }),
  HEALTH_BAR: Object.freeze({ MAX_HEALTH_FALLBACK: 100 }),
  DEFAULT_REMOTE_WEAPON_ID: 1,
});
