// src/config/weapons.js

export const FIRE_MODE = Object.freeze({ SEMI: 'semi', AUTO: 'auto' });

export const WEAPON_CONFIG = Object.freeze({
  PISTOL: { ID: 1, SLOT: 0, NAME: 'Pistol', FIRE_RATE_MS: 280, DAMAGE: 30, MAGAZINE_SIZE: 12, RESERVE_AMMO: 36, RELOAD_TIME_MS: 1600, RANGE: 100, MUZZLE_VELOCITY: 320, DAMAGE_FALLOFF_START: 25, DAMAGE_FALLOFF_END: 100, MIN_DAMAGE_MULTIPLIER: 0.55, RECOIL_PITCH: 0.042, RECOIL_YAW_SPREAD: 0.012, SPREAD_BASE: 0, STEADY_SPREAD: 0.006, SPREAD_GROW: 0.01, SPREAD_MAX: 0.045, SPREAD_DECAY: 0.14, PELLETS: 1, FIRE_MODE: FIRE_MODE.SEMI, SFX: 'pistol' },
  SMG: { ID: 2, SLOT: 1, NAME: 'SMG', FIRE_RATE_MS: 75, DAMAGE: 13, MAGAZINE_SIZE: 30, RESERVE_AMMO: 90, RELOAD_TIME_MS: 2000, RANGE: 75, MUZZLE_VELOCITY: 290, DAMAGE_FALLOFF_START: 18, DAMAGE_FALLOFF_END: 75, MIN_DAMAGE_MULTIPLIER: 0.45, RECOIL_PITCH: 0.02, RECOIL_YAW_SPREAD: 0.022, SPREAD_BASE: 0, STEADY_SPREAD: 0.009, SPREAD_GROW: 0.014, SPREAD_MAX: 0.08, SPREAD_DECAY: 0.16, PELLETS: 1, FIRE_MODE: FIRE_MODE.AUTO, SFX: 'smg' },
  SHOTGUN: { ID: 3, SLOT: 2, NAME: 'Shotgun', FIRE_RATE_MS: 850, DAMAGE: 11, MAGAZINE_SIZE: 6, RESERVE_AMMO: 24, RELOAD_TIME_MS: 2600, RANGE: 30, MUZZLE_VELOCITY: 230, DAMAGE_FALLOFF_START: 7, DAMAGE_FALLOFF_END: 30, MIN_DAMAGE_MULTIPLIER: 0.35, RECOIL_PITCH: 0.1, RECOIL_YAW_SPREAD: 0.035, SPREAD_BASE: 0.045, STEADY_SPREAD: 0.012, SPREAD_GROW: 0.012, SPREAD_MAX: 0.11, SPREAD_DECAY: 0.22, PELLETS: 8, FIRE_MODE: FIRE_MODE.SEMI, SFX: 'shotgun' },
  RIFLE: { ID: 4, SLOT: 3, NAME: 'Rifle', FIRE_RATE_MS: 95, DAMAGE: 24, MAGAZINE_SIZE: 25, RESERVE_AMMO: 75, RELOAD_TIME_MS: 2200, RANGE: 160, MUZZLE_VELOCITY: 760, DAMAGE_FALLOFF_START: 55, DAMAGE_FALLOFF_END: 160, MIN_DAMAGE_MULTIPLIER: 0.65, RECOIL_PITCH: 0.03, RECOIL_YAW_SPREAD: 0.011, SPREAD_BASE: 0, STEADY_SPREAD: 0.0045, SPREAD_GROW: 0.009, SPREAD_MAX: 0.05, SPREAD_DECAY: 0.11, PELLETS: 1, FIRE_MODE: FIRE_MODE.AUTO, SFX: 'rifle' },
});

export const WEAPON_LOADOUT = Object.freeze([
  WEAPON_CONFIG.PISTOL,
  WEAPON_CONFIG.SMG,
  WEAPON_CONFIG.SHOTGUN,
  WEAPON_CONFIG.RIFLE,
]);

export const DEFAULT_WEAPON = WEAPON_CONFIG.PISTOL;
