// src/network/PeerManager.js

import { Peer } from 'peerjs';
import { PACKET_TYPES } from './PacketTypes.js';

/**
 * PeerManager wraps PeerJS to handle WebRTC DataChannel connections, 
 * room creation, signaling, and raw binary network I/O between Host and Clients.
 */
export class PeerManager {
  constructor() {
    this.peer = null;
    this.connections = new Map(); // Map<peerId, DataConnection>
    this.isHost = false;
    this.onDataCallback = null;
    this.onConnectCallback = null;
    this.onDisconnectCallback = null;
  }

  /**
   * Initializes the Host peer instance and sets up connection listeners.
   * @param {string} [customRoomId] - Optional explicit room code.
   * @returns {Promise<string>} Generated or assigned Room Peer ID.
   */
  initHost(customRoomId = null) {
    this.isHost = true;
    return new Promise((resolve, reject) => {
      this.peer = customRoomId ? new Peer(customRoomId) : new Peer();

      this.peer.on('open', (id) => {
        this._setupHostListeners();
        resolve(id);
      });

      this.peer.on('error', (err) => {
        reject(err);
      });
    });
  }

  /**
   * Alias method for initHost to match HostGame API expectations.
   * @param {string} [customRoomId]
   * @returns {Promise<string>}
   */
  initializeHost(customRoomId = null) {
    return this.initHost(customRoomId);
  }

  /**
   * Initializes a Client peer instance and connects to a Host room ID.
   * @param {string} hostPeerId - Room code generated by the Host.
   * @returns {Promise<void>}
   */
  initClient(hostPeerId) {
    this.isHost = false;
    return new Promise((resolve, reject) => {
      this.peer = new Peer();

      this.peer.on('open', () => {
        // Create unreliable, unordered WebRTC DataChannel connection (UDP-like behavior)
        const conn = this.peer.connect(hostPeerId, {
          reliable: false,
          serialization: 'none', // Raw ArrayBuffers
        });

        conn.on('open', () => {
          this.connections.set(hostPeerId, conn);
          this._setupConnectionListeners(conn, hostPeerId);
          if (this.onConnectCallback) this.onConnectCallback(hostPeerId);
          resolve();
        });

        conn.on('error', (err) => {
          reject(err);
        });
      });

      this.peer.on('error', (err) => {
        reject(err);
      });
    });
  }

  /**
   * Alias method for initClient to match ClientGame API expectations.
   * @param {string} hostPeerId
   * @returns {Promise<void>}
   */
  initializeClient(hostPeerId) {
    return this.initClient(hostPeerId);
  }

  /**
   * Registers incoming connection handler for Host mode.
   * @private
   */
  _setupHostListeners() {
    this.peer.on('connection', (conn) => {
      conn.on('open', () => {
        this.connections.set(conn.peer, conn);
        this._setupConnectionListeners(conn, conn.peer);
        if (this.onConnectCallback) this.onConnectCallback(conn.peer);
      });
    });
  }

  /**
   * Binds data and disconnect events to a DataConnection instance.
   * @private
   */
  _setupConnectionListeners(conn, peerId) {
    conn.on('data', (data) => {
      if (this.onDataCallback && data instanceof ArrayBuffer) {
        this.onDataCallback(peerId, new DataView(data));
      }
    });

    conn.on('close', () => {
      this.connections.delete(peerId);
      if (this.onDisconnectCallback) this.onDisconnectCallback(peerId);
    });

    conn.on('error', () => {
      this.connections.delete(peerId);
      if (this.onDisconnectCallback) this.onDisconnectCallback(peerId);
    });
  }

  /**
   * Transmits a binary payload to a specific connected peer.
   * @param {string} peerId 
   * @param {ArrayBuffer} buffer 
   */
  sendTo(peerId, buffer) {
    const conn = this.connections.get(peerId);
    if (conn && conn.open) {
      conn.send(buffer);
    }
  }

  /**
   * Broadcasts a binary payload to all connected peers (Host use-case).
   * @param {ArrayBuffer} buffer 
   */
  broadcast(buffer) {
    this.connections.forEach((conn) => {
      if (conn.open) {
        conn.send(buffer);
      }
    });
  }

  /**
   * Sets callback fired when binary network packet is received.
   * @param {function(peerId: string, view: DataView): void} cb 
   */
  onData(cb) {
    this.onDataCallback = cb;
  }

  /**
   * Sets callback fired when a new peer connects.
   * @param {function(peerId: string): void} cb 
   */
  onConnect(cb) {
    this.onConnectCallback = cb;
  }

  /**
   * Alias method for onConnect.
   * @param {function(peerId: string): void} cb 
   */
  onPeerConnect(cb) {
    this.onConnect(cb);
  }

  /**
   * Sets callback fired when a peer disconnects.
   * @param {function(peerId: string): void} cb 
   */
  onDisconnect(cb) {
    this.onDisconnectCallback = cb;
  }

  /**
   * Alias method for onDisconnect.
   * @param {function(peerId: string): void} cb 
   */
  onPeerDisconnect(cb) {
    this.onDisconnect(cb);
  }

  /**
   * Closes all peer connections and destroys the peer instance.
   */
  destroy() {
    this.connections.forEach((conn) => conn.close());
    this.connections.clear();
    if (this.peer) {
      this.peer.destroy();
    }
  }
}